Document: statsite
Title: Debian statsite Manual
Author: <insert document author here>
Abstract: This manual describes what statsite is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/statsite/statsite.sgml.gz

Format: postscript
Files: /usr/share/doc/statsite/statsite.ps.gz

Format: text
Files: /usr/share/doc/statsite/statsite.text.gz

Format: HTML
Index: /usr/share/doc/statsite/html/index.html
Files: /usr/share/doc/statsite/html/*.html
